[package]
name = "macro-support"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
macro_state = "0.2"
aoc-core = "0.1"
